/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
public class addVaccine extends javax.swing.JFrame {
 ConnectionProvider conn;
    /**
     * Creates new form addVaccine
     */
    public addVaccine() {
        initComponents();
    }
     public addVaccine(String username) {
        initComponents();
          conn=new ConnectionProvider();
        if(conn==null)
        {
            JOptionPane.showMessageDialog(this,"DB connection not available","Error",JOptionPane.ERROR_MESSAGE);
        }
        jOwnerId.setText(username);
        jOwnerId.setEditable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jOwnerId = new javax.swing.JTextField();
        jPetId = new javax.swing.JTextField();
        jcentid = new javax.swing.JTextField();
        jLast = new javax.swing.JTextField();
        jNext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpecies = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Vaccine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("OwnID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 169, 103, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PetID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 217, 103, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 289, 59, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Vetcentre ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 259, 103, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Vaccine ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 103, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Last Dose");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 103, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Next Dose");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 103, -1));

        jOwnerId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jOwnerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOwnerIdActionPerformed(evt);
            }
        });
        getContentPane().add(jOwnerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 252, -1));

        jPetId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPetId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPetIdActionPerformed(evt);
            }
        });
        getContentPane().add(jPetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 252, -1));

        jcentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jcentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 252, -1));

        jLast.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 252, -1));

        jNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        getContentPane().add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 252, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 103, 33));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 103, 33));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 80, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Species");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 310, 103, -1));

        jSpecies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpeciesActionPerformed(evt);
            }
        });
        getContentPane().add(jSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOwnerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOwnerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOwnerIdActionPerformed

    private void jPetIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPetIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPetIdActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String last=jLast.getText();
        String next=jNext.getText();
        String vaccid=(String)jComboBox1.getSelectedItem();
        String petid=jPetId.getText();
        String date = jLast.getText();
        String date2=jNext.getText();
        String regex = "^((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)$" 
      + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
      + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$" 
      + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$";
        
        if(last.isEmpty()||next.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter all the details.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!date.matches(regex)|| !(date2.matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Enter date in YYYY-MM-DD format");
        }
        else
        {
        try
        {
            Connection dbconn=ConnectionProvider.getCon();
            Statement st=dbconn.createStatement();
            
            st.executeUpdate("insert into animalTreated values('"+petid+"','"+vaccid+"','"+last+"','"+next+"')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            setVisible(false);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Enter details in correct format");
        }
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String username=jOwnerId.getText();
         jOwnerId.setEditable(false);
         String petid=jPetId.getText();
         try{
            Connection dbconn=ConnectionProvider.getCon();
            Statement st=dbconn.createStatement();
            ResultSet rs1=st.executeQuery("select centid,animal from animals where ownid="+username+" and petid='"+petid+"'");
            if(rs1.next())
            {
                jcentid.setText(rs1.getString(1));
                jcentid.setEditable(false);
                jSpecies.setText(rs1.getString(2));
                jSpecies.setEditable(false);
                
                
                String vetcentid=jcentid.getText();
                String species=jSpecies.getText();
                
                 PreparedStatement pst=dbconn.prepareStatement("select * from addVaccine where centid="+vetcentid+" and animal='"+species+"' and vaccid not in(select vaccid from animalTreated where petid='"+petid+"')");
//                pst.setString(1,vetcentid);
//                 pst.setString(2,species);
                ResultSet rs=pst.executeQuery();
                while(rs.next()){
                String vaccid=rs.getString("vaccid");
                jComboBox1.addItem(vaccid);
                
            }
            }
            else
                {
                        JOptionPane.showMessageDialog(null, "PetId not found");
                 }       
                
                
            }
         
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpeciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLast;
    private javax.swing.JTextField jNext;
    private javax.swing.JTextField jOwnerId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPetId;
    private javax.swing.JTextField jSpecies;
    private javax.swing.JTextField jcentid;
    // End of variables declaration//GEN-END:variables
}
