/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
import Project.ConnectionProvider;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

public class updatePetRecord extends javax.swing.JFrame {
      ConnectionProvider conn;

    /**
     * Creates new form updatePetRecord
     */
    public updatePetRecord() {
        initComponents();
//        conn=new ConnectionProvider();
//        if(conn==null)
//        {
//            JOptionPane.showMessageDialog(this,"DB connection not available","Error",JOptionPane.ERROR_MESSAGE);
//        }
    }
    public updatePetRecord(String username) {
        initComponents();
        conn=new ConnectionProvider();
        if(conn==null)
        {
            JOptionPane.showMessageDialog(this,"DB connection not available","Error",JOptionPane.ERROR_MESSAGE);
        }
        jOwnerId.setText(username);
        jOwnerId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPetid = new javax.swing.JTextField();
        jPetname = new javax.swing.JTextField();
        jBreed = new javax.swing.JTextField();
        jOwnerId = new javax.swing.JTextField();
        jBloodgrp = new javax.swing.JTextField();
        jAge = new javax.swing.JTextField();
        jLast = new javax.swing.JTextField();
        jNext = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSpecies = new javax.swing.JTextField();
        jGender = new javax.swing.JTextField();
        jVetcentreid = new javax.swing.JTextField();
        jVaccineid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(430, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pet ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 139, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pet Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 139, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Species");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 139, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 197, 95, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Breed");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 139, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 139, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Owner ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 139, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Blood Group");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 139, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Age");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 139, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Veterinary Centre ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Vaccine ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 139, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Last Dose Taken");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 139, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Next Dose");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 139, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 93, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 90, -1));

        jPetid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPetidActionPerformed(evt);
            }
        });
        getContentPane().add(jPetid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 250, -1));

        jPetname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPetnameActionPerformed(evt);
            }
        });
        getContentPane().add(jPetname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 250, -1));
        getContentPane().add(jBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 250, -1));
        getContentPane().add(jOwnerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 250, -1));
        getContentPane().add(jBloodgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 250, -1));

        jAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeActionPerformed(evt);
            }
        });
        jAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAgeKeyPressed(evt);
            }
        });
        getContentPane().add(jAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 250, -1));

        jLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastActionPerformed(evt);
            }
        });
        getContentPane().add(jLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 250, -1));

        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });
        getContentPane().add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 250, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatepage.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 200));
        getContentPane().add(jSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 250, -1));
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 250, -1));
        getContentPane().add(jVetcentreid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 250, -1));
        getContentPane().add(jVaccineid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 250, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 140, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPetidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPetidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPetidActionPerformed

    private void jPetnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPetnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPetnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String petid=jPetid.getText();
        String username=jOwnerId.getText();
        
        try{
            Connection dbconn=ConnectionProvider.getCon();
            Statement st=dbconn.createStatement();
            ResultSet rs=st.executeQuery("select *from animals where ownid="+username+" and petid='"+petid+"'");
           
            
            if(rs.next())
            {
                jPetname.setText(rs.getString(4));
                jBreed.setText(rs.getString(3));
//                jOwnerId.setText(rs.getString(8));
                jBloodgrp.setText(rs.getString(7));
                jAge.setText(rs.getString(6));
                jVetcentreid.setText(rs.getString(9));
                
                jSpecies.setText(rs.getString(2));
                jGender.setText(rs.getString(5));
                jOwnerId.setEditable(false);
                jPetid.setEditable(false);
                
            }
              else
            {
                JOptionPane.showMessageDialog(null, "Petid does not exits");
            }
              
            Statement st1=dbconn.createStatement();
            ResultSet rs1=st1.executeQuery("select *from animalTreated at,animals a where a.petid=at.petid and a.ownid="+username+" and at.petid='"+petid+"'");
            if(rs1.next())
            {
                jVaccineid.setText(rs1.getString(2));
                jLast.setText(rs1.getString(3));
                jNext.setText(rs1.getString(4));
                
                
            }
             jVaccineid.setEditable(false);
        jVetcentreid.setEditable(false);
            
            
//            else
//            {
//                JOptionPane.showMessageDialog(null, "Petid does not exits");
//            }
//                
               
                      
               
                
           
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String petid=jPetid.getText();
        String species=jSpecies.getText();
        String petname=jPetname.getText();
        String breed=jBreed.getText();
        String gender=jGender.getText();
        String ownerid=jOwnerId.getText();
        String bloodgrp=jBloodgrp.getText();
        String last=jLast.getText();
        String next=jNext.getText();
        String vaccid=jVaccineid.getText();
        String age=jAge.getText();
        String vetcentreid=jVetcentreid.getText();
        String date = jLast.getText();
        String next1=jNext.getText();
        String regex = "^((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)$" 
      + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
      + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$" 
      + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$";
        
        if(petid.isEmpty()||petname.isEmpty()||breed.isEmpty()||species.isEmpty()||bloodgrp.isEmpty()||age.isEmpty()||last.isEmpty()||next.isEmpty()||gender.isEmpty()||vetcentreid.isEmpty()||vaccid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter all the details.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if(!date.matches(regex)|| !(next1.matches(regex)))
        {
            JOptionPane.showMessageDialog(null,"Enter date in YYYY-MM-DD format");
        }
        else
        {
        try{
            Connection dbconn=ConnectionProvider.getCon();
            Statement st=dbconn.createStatement();
            st.executeUpdate("update animals set animal='"+species+"', breed='"+breed+"', petname='"+petname+"',gender='"+gender+"',age="+age+",bloodgrp='"+bloodgrp+"' where petid='"+petid+"'");
            Statement st1=dbconn.createStatement();

            st1.executeUpdate("update animalTreated set lastdose='"+last+"',nextdose='"+next+"' where petid='"+petid+"' and vaccid='"+vaccid+"'");
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new updatePetRecord().setVisible(false);
        }
        catch(Exception e )
        {
            JOptionPane.showMessageDialog(null,"Enter deatils in correct Format");
        }
           
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jAgeActionPerformed

    private void jAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgeKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            jAge.setEditable(false);
            jLabel14.setText("Enter Numeric Value");
            
            
        }
        else
        {
            jAge.setEditable(true);
        }
    }//GEN-LAST:event_jAgeKeyPressed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextActionPerformed

    private void jLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatePetRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatePetRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatePetRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatePetRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatePetRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField jAge;
    private javax.swing.JTextField jBloodgrp;
    private javax.swing.JTextField jBreed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLast;
    private javax.swing.JTextField jNext;
    private javax.swing.JTextField jOwnerId;
    private javax.swing.JTextField jPetid;
    private javax.swing.JTextField jPetname;
    private javax.swing.JTextField jSpecies;
    private javax.swing.JTextField jVaccineid;
    private javax.swing.JTextField jVetcentreid;
    // End of variables declaration//GEN-END:variables
}
