/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
import javax.swing.JOptionPane;
import Project.ConnectionProvider;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class vetcenRegister extends javax.swing.JFrame {

    /**
     * Creates new form vetcenRegister
     */
    public vetcenRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jVetid = new javax.swing.JTextField();
        jcentname = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        iEmailid = new javax.swing.JTextField();
        jPhoneno = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Register");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vet ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 53, 125, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Centre Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 125, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 171, 125, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 227, 125, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Email ID");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 284, 125, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Phone No");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 347, 125, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Back to Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 133, -1));

        jVetid.setEditable(false);
        jVetid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jVetid.setText("Don't Enter! Auto Generated ID");
        jVetid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVetidActionPerformed(evt);
            }
        });
        jPanel3.add(jVetid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 250, -1));

        jcentname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcentname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcentnameKeyReleased(evt);
            }
        });
        jPanel3.add(jcentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 250, -1));

        jAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddressMouseClicked(evt);
            }
        });
        jPanel3.add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 250, -1));

        iEmailid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(iEmailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 250, -1));

        jPhoneno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPhoneno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPhonenoMouseClicked(evt);
            }
        });
        jPhoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhonenoKeyPressed(evt);
            }
        });
        jPanel3.add(jPhoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 250, -1));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel3.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 160, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String password=jPasswordField1.getText();
        String name=jcentname.getText();
        String address=jAddress.getText();
        String email=iEmailid.getText();
        String phno=jPhoneno.getText();
        
                
        if(password.isEmpty() || name.isEmpty() || address.isEmpty() || email.isEmpty() || phno.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this,"Fill up the form properly.","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            vetRegister(password,name,address,email,phno);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         dispose();
        vetcentreLogin l=new vetcentreLogin();
        l.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jVetidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVetidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVetidActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
            jPasswordField1.setEchoChar((char)0);
        } else 
        
        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
         if(jLabel8.getText()!=null)
        {
            JOptionPane.showMessageDialog(null,"Name can contain only uppercase,lowercase character or digit");
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jcentnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcentnameKeyReleased
        // TODO add your handling code here:
        String patt="[a-zA-Z0-9\\s]+";
        Pattern p=Pattern.compile(patt);
        Matcher match=p.matcher(jcentname.getText());
        if(!match.matches()){
          
            
            jLabel8.setText("Naming is incorect");
        }
        else
        {
           
            jLabel8.setText(null);
        }
    }//GEN-LAST:event_jcentnameKeyReleased

    private void jAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddressMouseClicked
        // TODO add your handling code here:
        String regex="^(?=.*[0-9])"
                       + "(?=.*[a-z])(?=.*[A-Z])"

                       + "(?=.*[@#$%&*])"

                       + "(?=\\S+$).{8,25}$"; 

        Pattern p=Pattern.compile(regex);
        Matcher match=p.matcher(jPasswordField1.getText());
        if(!match.matches()){
            JOptionPane.showMessageDialog(null,"Password must contain atleast 8 character,one uppercase,lowercase,digit and special character(@,#,%,*,&)");
            
        }
        
        
    }//GEN-LAST:event_jAddressMouseClicked

    private void jPhonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhonenoKeyPressed
        // TODO add your handling code here:
        String phoneno=jPhoneno.getText();
        int length=phoneno.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9')
        {
            if(length<10)
            {
                jPhoneno.setEditable(true);
                
            }
            else
            {
                jPhoneno.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                jPhoneno.setEditable(true);
            }
            else{
                jPhoneno.setEditable(false);
            }
        }
                
    }//GEN-LAST:event_jPhonenoKeyPressed

    private void jPhonenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPhonenoMouseClicked
        // TODO add your handling code here:
        String regex="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+(\\.[a-zA-Z]{2,4})";
    Pattern p=Pattern.compile(regex);
    Matcher match=p.matcher(iEmailid.getText());
     if(!match.matches()){
            JOptionPane.showMessageDialog(null,"Email Id should be of the form xxx@yyy.zzz");
            
        }
     
    }//GEN-LAST:event_jPhonenoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vetcenRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vetcenRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vetcenRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vetcenRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vetcenRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField iEmailid;
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jPhoneno;
    private javax.swing.JTextField jVetid;
    private javax.swing.JTextField jcentname;
    // End of variables declaration//GEN-END:variables

    private void vetRegister(String password, String name, String address, String email, String phno) {
         Connection dbconn=ConnectionProvider.getCon();
        try {
            PreparedStatement st=(PreparedStatement)dbconn.prepareStatement("insert into vetcentre(cname,centemail,cenphone,caddress,password) values(?,?,?,?,?)");
            
            
            st.setString(1, name);
          
            st.setString(2, email);
            st.setString(3, phno);
            st.setString(4, address);
            st.setString(5,password);
          
            int res=st.executeUpdate();
            JOptionPane.showMessageDialog(this,"Veterinary centre data inserted Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            PreparedStatement sti=dbconn.prepareStatement("select centid from vetcentre where cname=?");
            sti.setString(1,name);
            ResultSet rs = sti.executeQuery();
            while (rs.next ( ))
                {
                   String category = rs.getString("centid");
                   jVetid.setText(category);
                }
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }
        
}
